name: print Secret Variable
on: [push, workflow_dispatch]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          source: ./scripts/run.sh
          target: .
          script: chmod +x run.sh && ./run.sh
