name: print Secret Variable
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: print Secret
        env:
          super_secret: ${{ secrets.MY_SECRET }}
        run: echo ${{super_secret}}
